import streamlit as st
import pandas as pd
import numpy as np
import os
from datetime import datetime

st.set_page_config(page_title="Elliott Wave Screener — NASDAQ Composite", layout="wide")

OUTPUT_XLSX = "Elliott_Wave_NASDAQ_Composite_Master_Workbook.xlsx"

st.title("📈 Elliott Wave Trading Screener")
st.caption("Results auto-generated by a scheduled GitHub Action — this page only reads the latest file, it never runs the scan itself.")

st.markdown("""
<style>
table.ew-table {
    border-collapse: collapse;
    width: 100%;
    font-size: 13px;
    font-family: "Source Sans Pro", sans-serif;
}
table.ew-table th {
    background-color: #0D47A1;
    color: white;
    padding: 6px 8px;
    text-align: center;
    position: sticky;
    top: 0;
    border: 1px solid #90A4AE;
}
table.ew-table td {
    padding: 5px 8px;
    text-align: center;
    border: 1px solid #CFD8DC;
    white-space: nowrap;
}
table.ew-table tr:nth-child(even) td {
    background-color: #F7F7F7;
}
.ew-scroll {
    max-height: 650px;
    overflow: auto;
    border: 1px solid #90A4AE;
    border-radius: 4px;
}
</style>
""", unsafe_allow_html=True)


def dedupe_columns(cols):
    clean = []
    for c in cols:
        if pd.isna(c) or str(c).strip() == "" or str(c).lower() == "nan":
            clean.append("Unnamed")
        else:
            clean.append(str(c))
    counts = {}
    result = []
    for col in clean:
        if col in counts:
            counts[col] += 1
            result.append(f"{col}_{counts[col]}")
        else:
            counts[col] = 0
            result.append(col)
    return result


@st.cache_data(ttl=300)
def load_workbook():
    if not os.path.exists(OUTPUT_XLSX):
        return {}, None

    mtime = datetime.fromtimestamp(os.path.getmtime(OUTPUT_XLSX))
    sheets = pd.read_excel(OUTPUT_XLSX, sheet_name=None, engine="openpyxl")

    cleaned = {}
    for name, df in sheets.items():
        try:
            df2 = df.copy()
            df2.columns = df2.iloc[1] if df2.shape[0] > 1 else df2.columns
            df2 = df2.iloc[2:].reset_index(drop=True)
            df2.columns = dedupe_columns(df2.columns)
            df2 = df2.where(pd.notna(df2), "")
            cleaned[name] = df2
        except Exception:
            cleaned[name] = df

    return cleaned, mtime


def score_bg(val):
    try:
        v = float(val)
    except Exception:
        return None
    if v >= 88:
        return "#00C853", "white"
    if v >= 78:
        return "#64DD17", "black"
    if v >= 68:
        return "#FFD600", "black"
    return "#FF6D00", "white"


def state_bg(val):
    s = str(val).upper()
    if "3RD OF 3RD" in s or "EXPLOSIVE" in s:
        return "#00E5FF", "black"
    if "WAVE 3" in s or "BREAKOUT" in s:
        return "#00C853", "white"
    if "WAVE 2" in s or "BUY ZONE" in s:
        return "#FF9800", "black"
    if "ACCUMULATION" in s or "CAPITULATION" in s:
        return "#B9F6CA", "black"
    if "TRIANGLE" in s:
        return "#B0BEC5", "black"
    if any(x in s for x in ["BEAR", "EXIT", "TRAP", "BLOWOFF"]):
        return "#EF5350", "white"
    return "#ECEFF1", "black"


def action_bg(val):
    s = str(val).upper()
    if any(x in s for x in ["BUY", "LONG", "HOLD", "ADD", "BUILD"]):
        return "#00C853", "white"
    if any(x in s for x in ["EXIT", "AVOID", "SELL", "TRIM", "SHORT", "REDUCE"]):
        return "#EF5350", "white"
    return "#FFD600", "black"


SCORE_COLS = ["EWScore", "LTScore", "MTScore", "STScore", "MNScore",
              "CombinedScore", "TripleBullScore", "TomorrowBuyRank"]
STATE_COLS = ["ElliottState", "LTState", "MTState", "STState", "MNState"]
ACTION_COLS = ["RecommendedAction", "LTAction", "MTAction", "STAction", "MasterAction"]


def cell_style(col_name, val):
    if col_name in SCORE_COLS:
        r = score_bg(val)
    elif col_name in STATE_COLS:
        r = state_bg(val)
    elif col_name in ACTION_COLS:
        r = action_bg(val)
    else:
        r = None
    if r is None:
        return ""
    bg, fg = r
    return f"background-color:{bg}; color:{fg}; font-weight:600;"


def render_html_table(df):
    cols = list(df.columns)
    html = ['<div class="ew-scroll"><table class="ew-table"><thead><tr>']
    for c in cols:
        html.append(f"<th>{c}</th>")
    html.append("</tr></thead><tbody>")
    for _, row in df.iterrows():
        html.append("<tr>")
        for c in cols:
            val = row[c]
            style = cell_style(c, val)
            html.append(f'<td style="{style}">{val}</td>')
        html.append("</tr>")
    html.append("</tbody></table></div>")
    return "".join(html)


def apply_excel_style_filters(df, key_prefix):
    filtered = df.copy()
    with st.expander("🔎 Filters (click to expand)", expanded=False):
        cols_per_row = 4
        col_list = list(df.columns)
        for i in range(0, len(col_list), cols_per_row):
            row_cols = st.columns(cols_per_row)
            for j, col_name in enumerate(col_list[i:i + cols_per_row]):
                with row_cols[j]:
                    series = filtered[col_name]
                    nunique = series.nunique(dropna=True)

                    numeric_series = pd.to_numeric(series, errors="coerce")
                    is_numeric = numeric_series.notna().sum() >= max(1, int(len(series) * 0.7))

                    if is_numeric and nunique > 15:
                        valid = numeric_series.dropna()
                        if not valid.empty:
                            lo, hi = float(valid.min()), float(valid.max())
                            if lo < hi:
                                sel = st.slider(
                                    col_name, min_value=lo, max_value=hi,
                                    value=(lo, hi), key=f"{key_prefix}_{col_name}_slider"
                                )
                                mask = numeric_series.between(sel[0], sel[1]) | series.isna()
                                filtered = filtered[mask]
                    elif 0 < nunique <= 40:
                        options = sorted(series.dropna().astype(str).unique().tolist())
                        selected = st.multiselect(
                            col_name, options, default=options,
                            key=f"{key_prefix}_{col_name}_multi"
                        )
                        if selected and len(selected) < len(options):
                            filtered = filtered[series.astype(str).isin(selected)]
                    else:
                        text = st.text_input(
                            f"{col_name} contains", key=f"{key_prefix}_{col_name}_text"
                        )
                        if text:
                            filtered = filtered[series.astype(str).str.contains(text, case=False, na=False)]
    return filtered


sheets_dict, last_updated = load_workbook()

if last_updated:
    st.caption(f"Last data refresh: {last_updated:%Y-%m-%d %H:%M} (auto-updated every few hours by GitHub Actions)")

if st.button("🔄 Reload page data"):
    st.cache_data.clear()
    st.rerun()

(main_tab,) = st.tabs(["Nasdaq_Composite"])

with main_tab:
    if not sheets_dict:
        st.warning(
            "No results file found yet. The scheduled GitHub Action may not have "
            "run yet, or the workbook filename doesn't match. Check the Actions tab "
            "in your repo, or run the workflow manually (workflow_dispatch)."
        )
    else:
        tab_names = list(sheets_dict.keys())
        tabs = st.tabs(tab_names)

        for tab, name in zip(tabs, tab_names):
            with tab:
                df = sheets_dict[name]

                if df is None or df.empty:
                    st.info(f"No rows available for {name}.")
                    continue

                quick_search = st.text_input(
                    f"Quick search across all columns ({name})",
                    key=f"quick_{name}"
                )
                view = df
                if quick_search:
                    mask = df.apply(
                        lambda col: col.astype(str).str.contains(quick_search, case=False, na=False)
                    )
                    view = df[mask.any(axis=1)]

                view = apply_excel_style_filters(view, key_prefix=name)

                sort_cols = ["(none)"] + list(view.columns)
                c1, c2 = st.columns([3, 1])
                with c1:
                    sort_col = st.selectbox("Sort by", sort_cols, key=f"sortcol_{name}")
                with c2:
                    sort_dir = st.radio("Order", ["Desc", "Asc"], horizontal=True, key=f"sortdir_{name}")
                if sort_col != "(none)":
                    try:
                        numeric_try = pd.to_numeric(view[sort_col], errors="coerce")
                        if numeric_try.notna().sum() >= max(1, int(len(view) * 0.7)):
                            view = view.assign(_sortval=numeric_try).sort_values(
                                "_sortval", ascending=(sort_dir == "Asc")
                            ).drop(columns="_sortval")
                        else:
                            view = view.sort_values(sort_col, ascending=(sort_dir == "Asc"))
                    except Exception:
                        pass

                st.caption(f"Showing {len(view)} of {len(df)} rows")

                MAX_ROWS = 500
                display_view = view.head(MAX_ROWS)
                if len(view) > MAX_ROWS:
                    st.info(f"Displaying first {MAX_ROWS} rows. Use filters above to narrow results, or download full CSV below.")

                st.markdown(render_html_table(display_view), unsafe_allow_html=True)

                st.download_button(
                    f"Download {name} as CSV (all {len(view)} filtered rows)",
                    view.to_csv(index=False),
                    file_name=f"{name}.csv",
                    mime="text/csv",
                    key=f"dl_{name}"
                )
