import streamlit as st
import pandas as pd
import os
from datetime import datetime

st.set_page_config(page_title="Elliott Wave Screener — NASDAQ Composite", layout="wide")

OUTPUT_XLSX = "Elliott_Wave_NASDAQ_Composite_Master_Workbook.xlsx"

st.title("📈 Elliott Wave Trading Screener")
st.caption("Results auto-generated by a scheduled GitHub Action — this page only reads the latest file.")

@st.cache_data(ttl=300)
def load_workbook():
    if not os.path.exists(OUTPUT_XLSX):
        return {}, None
    mtime = datetime.fromtimestamp(os.path.getmtime(OUTPUT_XLSX))
    sheets = pd.read_excel(OUTPUT_XLSX, sheet_name=None, engine="openpyxl")
    cleaned = {}
    for name, df in sheets.items():
        try:
            df2 = df.copy()
            df2.columns = df2.iloc[1] if df2.shape[0] > 1 else df2.columns
            df2 = df2.iloc[2:].reset_index(drop=True)
            cleaned[name] = df2
        except Exception:
            cleaned[name] = df
    return cleaned, mtime

sheets_dict, last_updated = load_workbook()

if last_updated:
    st.caption(f"Last data refresh: {last_updated:%Y-%m-%d %H:%M}")

if st.button("🔄 Reload page data"):
    st.cache_data.clear()
    st.rerun()

(main_tab,) = st.tabs(["Nasdaq_Composite"])

with main_tab:
    if not sheets_dict:
        st.warning("No results file found yet. Check the Actions tab in your repo.")
    else:
        tab_names = list(sheets_dict.keys())
        tabs = st.tabs(tab_names)
        for tab, name in zip(tabs, tab_names):
            with tab:
                df = sheets_dict[name]
                if df is None or df.empty:
                    st.info(f"No rows available for {name}.")
                    continue
                search = st.text_input(f"Filter {name}...", key=f"filter_{name}")
                view = df
                if search:
                    mask = df.apply(lambda col: col.astype(str).str.contains(search, case=False, na=False))
                    view = df[mask.any(axis=1)]
                st.dataframe(view, use_container_width=True, height=650)
                st.download_button(f"Download {name} as CSV", view.to_csv(index=False),
                                    file_name=f"{name}.csv", mime="text/csv", key=f"dl_{name}")
