import streamlit as st
import pandas as pd
import numpy as np
import os
import glob
from datetime import datetime

# INCREASE MAX RENDER ELEMENTS TO FIX STREAMLITAPIEXCEPTION
pd.set_option("styler.render.max_elements", 9_999_999)

st.set_page_config(page_title="Elliott Wave Screener", layout="wide")

st.title("\U0001F4C8 Elliott Wave Trading Screener")
st.caption("Results auto-generated by a scheduled GitHub Action.")

# Columns to show ONLY on the Dashboard tab. All other tabs remain AS-IS.
DASHBOARD_COLUMNS = [
    "Symbol",
    "Price ($)",
    "Elliott Degree",
    "Action Comment",
    "BUY TFs #",
    "SELL TFs #",
    "BUY Timeframes Hit",
    "SELL Timeframes Hit",
    "BUY Timeframes Hit Dates",
    "SELL Timeframes Hit Dates",
    "Latest BUY Date (any TF)",
    "BUY Date Timeframe",
    "Latest SELL Date (any TF)",
    "SELL Date Timeframe",
    "Last Annual BUY Date",
    "Annual BUY Timeframe",
    "Annual BUY Count (10yr)",
    "Fundamental Strength",
    "Professor Note",
]

def dedupe_columns(cols):
    clean = []
    for c in cols:
        c_str = str(c).strip()
        if pd.isna(c) or c_str == "" or c_str.lower() == "nan":
            clean.append("Unnamed")
        else:
            clean.append(c_str)
    counts = {}
    result = []
    for col in clean:
        if col in counts:
            counts[col] += 1
            result.append(f"{col}_{counts[col]}")
        else:
            counts[col] = 0
            result.append(col)
    return result

@st.cache_data(ttl=300)
def load_workbook():
    files = glob.glob("Elliott_Wave_NASDAQ_Composite_Master_Workbook*.xlsx")
    if not files:
        return {}, None

    latest_file = max(files, key=os.path.getmtime)
    mtime = datetime.fromtimestamp(os.path.getmtime(latest_file))
    sheets = pd.read_excel(latest_file, sheet_name=None, engine="openpyxl")

    cleaned = {}
    for name, df in sheets.items():
        try:
            df = df.dropna(how='all', axis=0).dropna(how='all', axis=1)

            if any('Unnamed' in str(c) for c in df.columns[:3]):
                for i in range(min(5, len(df))):
                    if df.iloc[i].notna().sum() > len(df.columns) / 2:
                        df.columns = df.iloc[i]
                        df = df.iloc[i+1:].reset_index(drop=True)
                        break

            df.columns = dedupe_columns(df.columns)
            df = df.where(pd.notna(df), "")
            cleaned[name] = df
        except Exception:
            cleaned[name] = df

    return cleaned, mtime

# Background coloring functions
def score_bg(val):
    try:
        v = float(str(val).replace(",", "").strip())
    except Exception:
        return None
    if v >= 88: return "#00C853", "white"
    if v >= 78: return "#64DD17", "black"
    if v >= 68: return "#FFD600", "black"
    if v > 0: return "#FF6D00", "white"
    return None

def state_bg(val):
    s = str(val).upper().strip()
    if not s or s == "NAN": return None
    if "3RD OF 3RD" in s or "EXPLOSIVE" in s: return "#00E5FF", "black"
    if "WAVE 3" in s or "BREAKOUT" in s: return "#00C853", "white"
    if "WAVE 2" in s or "BUY ZONE" in s: return "#FF9800", "black"
    if "ACCUMULATION" in s or "CAPITULATION" in s: return "#B9F6CA", "black"
    if "TRIANGLE" in s: return "#B0BEC5", "black"
    if any(x in s for x in ["BEAR", "EXIT", "TRAP", "BLOWOFF"]): return "#EF5350", "white"
    return "#ECEFF1", "black"

def action_bg(val):
    s = str(val).upper().strip()
    if not s or s == "NAN": return None
    if any(x in s for x in ["BUY", "LONG", "HOLD", "ADD", "BUILD"]): return "#00C853", "white"
    if any(x in s for x in ["EXIT", "AVOID", "SELL", "TRIM", "SHORT", "REDUCE"]): return "#EF5350", "white"
    return "#FFD600", "black"

SCORE_KEYWORDS = ["score", "rank"]
STATE_KEYWORDS = ["state"]
ACTION_KEYWORDS = ["action", "signal", "recommendation"]

def style_dataframe(df):
    """Applies Pandas Styler element-wise safely for Streamlit"""
    styler = df.style

    map_func = getattr(styler, "map", getattr(styler, "applymap", None))

    for col in df.columns:
        c_lower = str(col).lower()
        if any(k in c_lower for k in SCORE_KEYWORDS):
            map_func(lambda v: f"background-color: {score_bg(v)[0]}; color: {score_bg(v)[1]};" if score_bg(v) else "", subset=[col])
        elif any(k in c_lower for k in STATE_KEYWORDS):
            map_func(lambda v: f"background-color: {state_bg(v)[0]}; color: {state_bg(v)[1]};" if state_bg(v) else "", subset=[col])
        elif any(k in c_lower for k in ACTION_KEYWORDS):
            map_func(lambda v: f"background-color: {action_bg(v)[0]}; color: {action_bg(v)[1]};" if action_bg(v) else "", subset=[col])

    return styler

def apply_excel_style_filters(df, key_prefix):
    filtered = df.copy()
    with st.expander("\U0001F50E Global Filters & Search", expanded=False):
        quick_search = st.text_input(f"Global Search ({key_prefix})", key=f"quick_{key_prefix}", placeholder="Type to search across all columns...")
        if quick_search:
            mask = filtered.apply(lambda col: col.astype(str).str.contains(quick_search, case=False, na=False))
            filtered = filtered[mask.any(axis=1)]

        st.markdown("---")

        cols_per_row = 4
        col_list = list(df.columns)
        for i in range(0, len(col_list), cols_per_row):
            row_cols = st.columns(cols_per_row)
            for j, col_name in enumerate(col_list[i:i + cols_per_row]):
                with row_cols[j]:
                    series = filtered[col_name]
                    nunique = series.nunique(dropna=True)
                    numeric_series = pd.to_numeric(series, errors="coerce")
                    is_numeric = numeric_series.notna().sum() >= max(1, int(len(series) * 0.7))

                    if is_numeric and nunique > 15:
                        valid = numeric_series.dropna()
                        if not valid.empty:
                            lo, hi = float(valid.min()), float(valid.max())
                            if lo < hi:
                                sel = st.slider(col_name, min_value=lo, max_value=hi, value=(lo, hi), key=f"{key_prefix}_{col_name}_slider")
                                mask = numeric_series.between(sel[0], sel[1]) | series.isna()
                                filtered = filtered[mask]
                    elif 0 < nunique <= 40:
                        options = sorted(series.dropna().astype(str).unique().tolist())
                        selected = st.multiselect(col_name, options, default=options, key=f"{key_prefix}_{col_name}_multi")
                        if selected and len(selected) < len(options):
                            filtered = filtered[series.astype(str).isin(selected)]
    return filtered


# --- Main App Execution ---
sheets_dict, last_updated = load_workbook()

if last_updated:
    st.caption(f"Last data refresh: {last_updated:%Y-%m-%d %H:%M} EST")

if st.button("\U0001F504 Reload page data"):
    st.cache_data.clear()
    st.rerun()

if not sheets_dict:
    st.warning("No results file found. Check if the workflow completed successfully.")
else:
    tab_names = list(sheets_dict.keys())
    tabs = st.tabs(tab_names)

    for tab, name in zip(tabs, tab_names):
        with tab:
            df = sheets_dict[name]

            if df is None or df.empty:
                st.info(f"No rows available for {name}.")
                continue

            # Restrict to the specified columns ONLY on the Dashboard tab.
            # All other tabs remain unchanged (AS-IS).
            if str(name).strip().lower() == "dashboard":
                available_cols = [c for c in DASHBOARD_COLUMNS if c in df.columns]
                missing_cols = [c for c in DASHBOARD_COLUMNS if c not in df.columns]
                if missing_cols:
                    st.caption(f"\u26A0\uFE0F Columns not found in Dashboard sheet and skipped: {', '.join(missing_cols)}")
                df = df[available_cols]

            # Apply UI Filters
            view = apply_excel_style_filters(df, key_prefix=name)

            st.caption(f"Showing {len(view)} of {len(df)} rows. Click column headers to sort.")

            # Create Pandas Style object for coloring
            styled_df = style_dataframe(view)

            # Native, paginated Streamlit DataFrame
            st.dataframe(
                styled_df,
                use_container_width=True,
                height=650,
                hide_index=True
            )

            st.download_button(
                f"\U0001F4E5 Download {name} Data as CSV",
                view.to_csv(index=False),
                file_name=f"{name}.csv",
                mime="text/csv",
                key=f"dl_{name}"
            )
